### ISSUE TITLE
Install instructions problem?

### ISSUE THREAD

**Issue by tychop** [Zingabopp/BeatSync#10]
Instructions say "Extract the release zip to your Beat Saber folder (or manually place BeatSync.dll into your Plugins folder)."
But that dll file does not exist in the zip.... (BeatSyncConsole v0.6.2)

**Comment by Zingabopp** [comment]
Yeah, that was for the old BeatSync mod. I haven't updated the readme yet to include BeatSyncConsole. For BeatSyncConsole, you can extra the folder anywhere (preferably somewhere in your user folder so avoid any NTFS file permissions issues) and run BeatSyncConsole.exe.

**Comment by Zingabopp** [comment]
Readme is updated, let me know if anything needs a better explanation.
