### ISSUE TITLE
BeatSync Case Sensitivity

### ISSUE THREAD

**Issue by Fidgetcetera** [Zingabopp/BeatSync#13]
The default game data folder that beatsync saves to is `Beat Saber_data/CustomLevels`, rather than `Beat Saber_Data/CustomLevels`.

This typo probably only matters on linux, and was fixable with a quick config change, but caused some frustration for me wondering why my songs wouldn't show up.

**Comment by C0rn3j** [comment]
Possible workaround for this since a release hasn't been made yet(replace your user):
```
ln -s "/home/c0rn3j/.local/share/Steam/steamapps/common/Beat Saber/Beat Saber_Data" "/home/c0rn3j/.local/share/Steam/steamapps/common/Beat Saber/Beat Saber_data"
```

**Comment by Fidgetcetera** [comment]
My personal way of handling this was to just edit BeatSyncConsole.json in the configs and just change GameDirectory and BasePath in the alternate song paths and beatsaber install locations. No need for symlinks when the config makes everything nice!
