### ISSUE TITLE
Question: Expected functionality for Replace PlaylistStyle

### ISSUE THREAD

**Issue by shikage** [Zingabopp/BeatSync#22]
When the PlaylistStyle is set to Replace what is the expected behavior? Should it retain the beat maps and only remove the songs from the playlist or should it remove the beat maps entirely? I ask mostly as I had intended to setup BeatSyncConsole to run as a scheduled task each day and get the most played and top ranked songs of the day but would like it to clear out old songs no longer on the list so that I don't have a quite rapidly growing list of songs that quickly becomes rather unmanageable.

**Comment by Zingabopp** [comment]
Replace means it'll clear the old playlist and replace it with the songs it reads from the feed (not just downloaded songs). Append means new songs that weren't on the playlist before will be added to it and it will keep the songs added on previous runs.
