### ISSUE TITLE
First run UX improvements

### ISSUE THREAD

**Issue by C0rn3j** [Zingabopp/BeatSync#23]
This is what I got on first run:
```
c0rn3j@Luxuria : ~/Downloads/BeatSyncConsole-0.8.1-linux-x64-63bb3ee/BeatSyncConsole
[0] % ./BeatSyncConsole       
[BeatSyncConsole - Info]: Starting BeatSyncConsole v0.8.1.0
[BeatSyncConsole - Info]: Running the latest release of BeatSyncConsole.
[BeatSyncConsole - Info]: configs/BeatSyncConsole.json not found, creating a new one.
[BeatSyncConsole - Info]: configs/BeatSync.json not found, creating a new one.
Would you like to replace the existing configs/BeatSync.json with a new one? (Y/N): 
Y
[BeatSyncConsole - Warn]: No enabled custom songs paths found, please manually enter a target directory for your songs in config.json.
[BeatSyncConsole - Info]: BeatSyncConsole cannot run without a valid config, exiting.
Stopping LogManager.
Press Enter to continue...
```

>Would you like to replace the existing configs/BeatSync.json with a new one? (Y/N): 

It does not exist, as the line above says, it should be reworded, or ideally just autodownload it if it does not exist.

>No enabled custom songs paths found, please manually enter a target directory for your songs in config.json

The default install path on Linux is:

```
~/.local/share/Steam/steamapps/common/Beat Saber
```
the app should check if this path exists, and if it does, autodetect and use it.

`config.json` is not a file this app uses. 
It is not clear to a new person from this message that they need to edit `GameDirectory` in `BeatSyncConsole.json`.
(Granted this is explained in the README)

Setting a GameDirectory that does not exist will result in the same Warn message, it should tell the user that the configured directory does not exist instead.

GameDirectory does not parse `~`, I had to manually write out `/home/c0rn3j/`

**Comment by Zingabopp** [comment]
I *think* I have everything fixed except for finding Beat Saber installs on Linux (coming soon:tm:). Can try it out here: https://github.com/Zingabopp/BeatSync/actions/runs/195889592

**Comment by Zingabopp** [comment]
Everything listed should be fixed in this release: https://github.com/Zingabopp/BeatSync/releases/tag/0.9.0

**Comment by C0rn3j** [comment]
Tried it, this is an infinitely better experience!
Thanks!
