### ISSUE TITLE
Some songs are not downloaded

### ISSUE THREAD

**Issue by cdytoby** [Zingabopp/BeatSync#24]
BeatSyncConsole 0.9.0  
Playlist username: cdytoby

By checking this list: https://bsaber.com/songs/new/page/8/?bookmarked_by=cdytoby  
I know I have 154 songs (20 per page and 14 in the last page), but the console only read 151 items.    
![image](https://user-images.githubusercontent.com/15671368/92323996-a5968d80-f03d-11ea-859e-babfb856a586.png)

I can't find all the songs are missing, however, I can confirm this song is missing:  
https://bsaber.com/songs/1e1/

Here is my BeatSync config:

```
{
  "RegenerateConfig": false,
  "DownloadTimeout": 30,
  "MaxConcurrentDownloads": 2,
  "RecentPlaylistDays": 7,
  "AllBeatSyncSongsPlaylist": false,
  "BeastSaber": {
    "Enabled": true,
    "Username": "cdytoby",
    "MaxConcurrentPageChecks": 10,
    "Bookmarks": {
      "Enabled": true,
      "MaxSongs": 0,
      "CreatePlaylist": true,
      "PlaylistStyle": "Append"
    },
    "Follows": {
      "Enabled": false,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Append"
    },
    "CuratorRecommended": {
      "Enabled": false,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Append"
    }
  },
  "BeatSaver": {
    "Enabled": false,
    "FavoriteMappers": {
      "Enabled": true,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Append",
      "SeparateMapperPlaylists": false
    },
    "Hot": {
      "Enabled": false,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Append"
    },
    "Downloads": {
      "Enabled": false,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Append"
    },
    "Latest": {
      "Enabled": false,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Append"
    }
  },
  "ScoreSaber": {
    "Enabled": false,
    "TopRanked": {
      "Enabled": true,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Replace",
      "IncludeUnstarred": true,
      "MaxStars": 0.0,
      "MinStars": 0.0
    },
    "LatestRanked": {
      "Enabled": true,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Replace",
      "IncludeUnstarred": true,
      "MaxStars": 0.0,
      "MinStars": 0.0
    },
    "Trending": {
      "Enabled": false,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Append",
      "RankedOnly": false,
      "IncludeUnstarred": true,
      "MaxStars": 0.0,
      "MinStars": 0.0
    },
    "TopPlayed": {
      "Enabled": false,
      "MaxSongs": 20,
      "CreatePlaylist": true,
      "PlaylistStyle": "Append",
      "RankedOnly": false,
      "IncludeUnstarred": true,
      "MaxStars": 0.0,
      "MinStars": 0.0
    }
  },
  "LastRun": "2020-09-06T12:31:33.0698541+02:00"
}
```

**Comment by zxsdklfhskyrvk** [comment]
I just used this to download from beastsaber as well, and noticed a similar gap in song count from the site (484), and what your code grabs (474).  This gap appears to be very close to the page count.  

cdytoby has just over 154 songs,  and reported 3 missing (154 / 50 = 3.xxx)
I have 484 songs and am missing 10. (484 / 50 = 9.xxxx)

I have to wonder if there is a bug in the API where it is only providing 49 songs per page, or if you are miscounting them by 1.

I'd suggest looking at that aspect of the code.

The other possibility is that there are somehow duplicates in beastsaber,  which doesn't seem likely,  but could happen.

**Comment by Zingabopp** [comment]
@cdytoby This may actually be a bug in BeastSaber's API. The song you listed isn't in the any of the pages in the API requests:
![image](https://user-images.githubusercontent.com/37518403/92330837-b0e6ba80-f037-11ea-9175-5df6b2db6fb1.png)

**Comment by zxsdklfhskyrvk** [comment]
Any chance you can increase the debug logging for that SongFeedReader?  That would help.  I think I found another missing song.  https://bsaber.com/songs/7027/

**Comment by zxsdklfhskyrvk** [comment]
Actually I did a simple API check.    The API seems to keep the results in order, no matter what (normally anyway).  I could be wrong here.

If you change the count from 50 to 20,  my missing song shows up.  It is a API bug.

#0 on this page should be song 7027. (by comparing my web view - https://bsaber.com/songs/new/page/3/?bookmarked_by=qucpjeqphxf0chmt9bhc)
https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=qucpjeqphxf0chmt9bhc&page=2&count=50

It appears as #8  on this page
https://bsaber.com/wp-json/bsaber-api/songs/?bookmarked_by=qucpjeqphxf0chmt9bhc&page=3&count=20

**Comment by cdytoby** [comment]
I want to inform you that I'm changing my playlist right now because I found some new songs. So now the list won't stay this way. For now the bug is not yet solved.

BTW I can't find the place to report beastsaber api issue except Discord channel. I'm very inactive there so I'll leave it to you. Thanks in advance.

**Comment by Zingabopp** [comment]
There's a BeastSaber Discord server, the bug has already been reported. Hopefully it gets fixed soon.

**Comment by zxsdklfhskyrvk** [comment]
I heard from the bsaber team,  and this appears to be fixed now.  @cdytoby   You should test and verify, but it fixed my issue with the beatsyncconsole app.

**Comment by cdytoby** [comment]
The number matches the count in BeastSaber website, so I believe this is solved. 

Thanks. I'll close the Ticket.

**Comment by gmonteir** [comment]
I am having this same issue. Was there an API change that broke this again?
