### ISSUE TITLE
Try 0: Rate limit exceeded on url

### ISSUE THREAD

**Issue by Tefery** [Zingabopp/BeatSync#27]
I don't know if it's a bug, but just in case I report it.
![bug](https://user-images.githubusercontent.com/25052654/100144913-cf6e8c00-2e97-11eb-9a54-9820a6da2e7e.png)
[bug.txt](https://github.com/Zingabopp/BeatSync/files/5592344/bug.txt)

**Comment by docwilco** [comment]
https://github.com/Zingabopp/BeatSaberDataProvider/pull/3 should fix it
