### ISSUE TITLE
Feature request: Add configuration option to disable extraction of zips

### ISSUE THREAD

**Issue by omeryagmurlu** [Zingabopp/BeatSync#29]
I believe I've got a niche problem here. For my workflow I need the unextracted .song zips. Currently I am rezipping everything after running beatsyncconsole.exe through a wrapper script, which honestly takes a while with lots of songs. Having the option to forego extraction would help me a lot. I know this is a really niche use case, but if it's trivial to implement, then maybe you could expose it as a configuration option.

Thanks for your work on this.

**Comment by Zingabopp** [comment]
You should already be able to do this with locations in `AlternateSongsPaths` (you can't using a `BeatSaberInstallLocation`). Just set `UnzipBeatmaps` to false in `BeatSyncConsole.json`.

**Comment by omeryagmurlu** [comment]
Oh, sorry. I can't understand how I overlooked that in the configuration. Wow
