### ISSUE TITLE
Error in DownloadJob.RunAsync

### ISSUE THREAD

**Issue by Nich0030** [Zingabopp/BeatSync#31]
Hi,

I get errors on all songs that BeatSync tries to download, the error is "Error in DownloadJob.RunAsync: The remove server returned 
an error: (522) Origin connection Time-out."
I have tried disabling my antivirus/firewall, re-downloaded BeatSyncConsole and setting the DownloadTimeout up to 60, but 
nothing has worked so far. any ideas as to what is causing it?

best regards.

**Comment by qStivi** [comment]
I have the same problem. I think it might be a bsaber problem because OneClick install also doesn't work. But downloading and extracting them manually seems to work mostly.

**Comment by Nich0030** [comment]
Ah okay, thanks for the response have had the problem for about a week i whould say.

**Comment by qStivi** [comment]
Seems to be fixed now :)
