### ISSUE TITLE
Sync issue - "The remove server returned an error: (401) Unauthorized."

### ISSUE THREAD

**Issue by Petymeg** [Zingabopp/BeatSync#33]
Hi,

I've used the mod successfully a few weeks ago, but when I tried to sync my favorites now I've ran into an issue that the new songs are not added to the library.

I've  attached the full log, but the most relevant part seems to be this:
```
[SongFeedReader - Debug]: Error getting https://beatsaver.com/api/download/hash/d19b4abf7d83d2882a5bf1f2bdc3b03491ef3eaf, 401 : Unauthorized. Skipping...
[BeatSyncLib - Warn]: Error in DownloadJob.RunAsync: The remove server returned an error: (401) Unauthorized.
[BeatSyncLib - Debug]:    at BeatSyncLib.Downloader.Downloading.DownloadJob.RunAsync(CancellationToken cancellationToken) in /home/runner/work/BeatSync/BeatSync/BeatSyncLib/Downloader/Downloading/DownloadJob.cs:line 146
[BeatSyncConsole - Info]:       Job failed: (D0BE) Bohemian Rhapsody - Queen by Jokidum
```

I assume something might have changed on BeastSaber's side, however I'm still not sure if this is user error (on my side) or config change.

[log.txt](https://github.com/Zingabopp/BeatSync/files/5753962/log.txt)

**Comment by M3X3M** [comment]
Same Issue here
[BeatSyncLib - Warn]: Error in DownloadJob.RunAsync: The remove server returned an error: (401) Unauthorized.
Doesn't seem to be on your side.

**Comment by Zingabopp** [comment]
BeatSaver's has temporarily disabled the API due to abuse by people scraping the site with randomized UserAgents. BeatSync won't work until it's enabled again.
________________________________

**Comment by justinforlenza** [comment]
Well it also just seems like their site is returning 401 for anything, but there are some mirror sites up, would be nice if we can set a custom URL for beatsaver, so mirror sites could be used.

**Comment by Tefery** [comment]
> BeatSaver has temporarily disabled the API due to abuse by people scraping the site with randomized UserAgents. BeatSync won't work until it's enabled again.

That assholes are going to force us to start logging in with credentials.

**Comment by lululombard** [comment]
I can't even create an account now :( And https://beatsaver.com/browse/hot doesn't load and returns a `HTTP/2 401 Unauthorized`

**Comment by lululombard** [comment]
Seems to have been fixed
