### ISSUE TITLE
BeatSync putting downloaded songs into the wrong directory

### ISSUE THREAD

**Issue by Ubivis** [Zingabopp/BeatSync#35]
Hi there, first thing first: wonderful job on this slick and simple Console Tool.

I have just freshly downloaded and unpacked it. Followed the instruction and set up an account on bsaber, put a few songs on my bookmark list and let the tool know my username and location of beat saber.

Download looked like working fine, but in game, I was not able to all to find the songs. Using the ingame-Downloader, I found that the games have to be put into the folder "CustomLevels", BeatSync on the other hand, seemed to have created another folder called "CustomLevels132550207275980127". After manually moving the files to the correct folder, all the songs shown up correctly.

Any idea why this could happen to me? (Only me so far?)

System:
- Windows 10 Professional
- BeatSync is running on another drive (and disk) than Beat Saber.

**Comment by Ubivis** [comment]
Small edit: after moving the files to the correct folder, deleting the one with the long name, all new files are now downloaded correctly.

**Comment by Zingabopp** [comment]
I believe that's actually the SongCore mod's Songe-Converter doing that. It detected an old format map in your CustomLevels folder and did a conversion.
