### ISSUE TITLE
BeatSyncConsole is not marked executable in Linux release

### ISSUE THREAD

**Issue by Xandaros** [Zingabopp/BeatSync#37]
Not a big deal, but I thought I'd mention it. Especially with the vast number of files in the archive, it took me a moment to figure out which file needed to be executed

**Comment by Zingabopp** [comment]
I'll see if i can fix that in the GitHub Action.

**Comment by Zingabopp** [comment]
Seems it won't be that easy, it's a limitation of GitHub's artifact uploading that file permissions are lost. I could tar it first, but that means you'd have to unzip and the extract the tar. Is that worth it?

**Comment by Zingabopp** [comment]
Fixed
