### ISSUE TITLE
Documentation for FavoriteMappers.ini file

### ISSUE THREAD

**Issue by Stevoisiak** [Zingabopp/BeatSync#42]
When running BeatSyncConsole as a new user, there are no instructions on how to add favorite mappers. The readme mentions this is pulled from FavoriteMappers.ini, but doesn't provide instructions for how this file should be formatted.

Is there documentation on how to create FavoriteMappers.ini file and how to add new mappers?

**Comment by fuyushi** [comment]
You just add one mapper name like it is on beatsaver per line

**Comment by Zingabopp** [comment]
Added instructions to the readme
