### ISSUE TITLE
Getting 403 on 0.9.3 but not on 0.9.1

### ISSUE THREAD

**Issue by C0rn3j** [Zingabopp/BeatSync#43]
![image](https://user-images.githubusercontent.com/1641362/118992954-628b0900-b985-11eb-942d-a01062674dd8.png)

Above is 0.9.3 failing and 0.9.1 running just fine

My configs are practically identical.

[configs_0.9.1.zip](https://github.com/Zingabopp/BeatSync/files/6516576/configs_0.9.1.zip)
[configs_0.9.3.zip](https://github.com/Zingabopp/BeatSync/files/6516579/configs_0.9.3.zip)

---

It should be "remote" server and not "remove" I assume

**Comment by Zingabopp** [comment]
This might be something you have to take up with the BeatSaver admins. Since it used to work and now it doesn't, I'm guessing they blocked your IP + BeatSyncConsole's UserAgent (just version 0.9.3). The BeatSyncConsole v0.9.3 release works on my PC.

**Comment by C0rn3j** [comment]
This was my first time using 0.9.3 and neither of my connections works

![image](https://user-images.githubusercontent.com/1641362/119096739-3f5b6a80-ba14-11eb-89b1-083d3518b151.png)

![image](https://user-images.githubusercontent.com/1641362/119096886-6f0a7280-ba14-11eb-94fb-c42b17592a5f.png)

**Comment by Vash63** [comment]
I'm seeing the same issue, first time using it (also on Linux, is the user agent different for Linux vs Windows builds?)

**Comment by Zingabopp** [comment]
What Linux distro are you using? It was working when I tested with Ubuntu.

**Comment by Vash63** [comment]
I'm on Arch. Is such a specific user agent really necessary? I'm not sure how to get in touch with BeatSaver to try and get mine whitelisted... the github says it's only for the code and not hosting issues.

**Comment by Zingabopp** [comment]
Nevermind, it doesn't work in Ubuntu anymore. Not sure what's going on, I thought Beat Saver used a blacklist not a whitelist. Guess I'll go back to the generic, boring User-Agent.

**Comment by Vash63** [comment]
That would be awesome if it worked. I was asking around in the BS mod Discord's #pc-help channel for a few days and didn't get a single reply on the topic of getting unblocked BeatSaver, tried multiple times and just crickets. I somewhat suspect it will need to just be Firefox or Chrome or something at this point as whoever runs it does not seem to be easy to contact (only contact info on the website is for DMCA and the github explicitely says they don't run the website, so no idea where to go for Cloudflare configuration issues).

**Comment by Zingabopp** [comment]
Actually, I think I might've just published the wrong tar.gz file for Linux in the Releases page. The latest Actions build works.

**Comment by Zingabopp** [comment]
This should be fixed in v0.9.4.

**Comment by Vash63** [comment]
Yes, it's working now, thanks!

**Comment by C0rn3j** [comment]
![image](https://user-images.githubusercontent.com/1641362/123615161-548e9a80-d805-11eb-957c-bbe9ad600d0a.png)

0.9.4 does indeed solve the problem, thank you.
