### ISSUE TITLE
Can't figure out why it just doesn't work anymore :(

### ISSUE THREAD

**Issue by Katjastrophic** [Zingabopp/BeatSync#44]
Hi!
So ever since a few months ago, the Console is no longer working for me - it worked perfectly fine up until recently.
Iirc, this started after I changed the install location of BS to another drive. It's now back on the drive I had it on originally (pretty sure at least), just reinstalled it, updated, all Mods are updated, too, but I still geterror messages. When I try to just leave it open and download songs from BeastSaber, it gives me an uncomprehensive error message (tells me it couldn't find the application). I am absolutely clueless about this stuff and I don't know what it wants me to do. Can you help? 

![grafik](https://user-images.githubusercontent.com/86541680/123530792-abf61300-d6fe-11eb-8d19-e101abdfe912.png)
![grafik](https://user-images.githubusercontent.com/86541680/123530846-67b74280-d6ff-11eb-9eec-bc3f192f801e.png)

**Comment by Zingabopp** [comment]
For game installs, you point it at the Beat Saber root folder (the one with `Beat Saber.exe`), not `Beat Saber_Data`.
