### ISSUE TITLE
BeatSaver API Change (BeatSync Not Working)

### ISSUE THREAD

**Issue by Zingabopp** [Zingabopp/BeatSync#45]
As announced in the Beat Saber Modding Group Discord server on Aug. 2nd, 2021, ownership of Beat Saver has been changed from the Jellyfish to Top_Cat. Along with the handover, there were some major changes to the site and API. This is a breaking change for anything using Beat Saver. I will hopefully have an update to accommodate these changes soon.

**Comment by Tommy2678** [comment]
Hello! I just got Beat Saber for steam right when this all happened, the servers are now up and working 😄  
I had it on quest before and was looking for something that was like the thing in BMBF and found this!
I can't wait to see if it works after the updates, thank you so much! :D

**Comment by Tommy2678** [comment]
Hey, has the update come out yet?

**Comment by Zingabopp** [comment]
It's unpolished, but the latest build should be working (Beat Saver `Hot` and `Downloads` feeds must be disabled in the config because they don't exist anymore) https://github.com/Zingabopp/BeatSync/actions

**Comment by Tommy2678** [comment]
Warn @ 2021-08-10 15:47:23 | BeatSyncLib]: Error in DownloadJob.RunAsync: The remote server returned an error: (404) Not Found.

that's all that happens, even if i disable it

**Comment by kinect360** [comment]
I'm getting the same error as tommy, just tried updating my files today.

**Comment by Epidilius** [comment]
Is there a way to get bookmarks working again? I pulled latest and rebuilt, and get "600/600 Skipped" for my bookmarks.

**Comment by Zingabopp** [comment]
For the 404 errors, try the latest build. Before it was using the beatmaps.io domain and it seems the redirect wasn't playing nice.

**Comment by rusozoll** [comment]
@Epidilius I don't know that it is the 'right' or even recommended way, but when I need to reset, I delete the history file.

steamapps\common\Beat Saber\UserData\BeatSyncHistory.json

Note: The last time I did that I had to rebuild my config file, but the time before that I didn't... I'm not sure what the expected response is, but you should probably make a copy of that just in case.

**Comment by Zingabopp** [comment]
> 
> 
> @Epidilius I don't know that it is the 'right' or even recommended way, but when I need to reset, I delete the history file.
> 
> steamapps\common\Beat Saber\UserData\BeatSyncHistory.json
> 
> Note: The last time I did that I had to rebuild my config file, but the time before that I didn't... I'm not sure what the expected response is, but you should probably make a copy of that just in case.

This. Bookmarks are working fine for me, if songs were skipped that means they're in your history as previously downloaded, you already have those songs, or there was an error downloading (each song's error would be in the log).

**Comment by Tommy2678** [comment]
beatsync inside bmbf doesn't work either. downloads playlists, sure, but no songs are actually downloaded. it's the same case when trying to download inside of beat saber on pc.

**Comment by Tommy2678** [comment]
deleting history doesn't work either.

https://pastebin.com/RkBdJFcu

**Comment by Zingabopp** [comment]
BMBF's SyncSaber/BeatSync probably hasn't been updated yet. I haven't been involved in its development since its initial release.

**Comment by Zingabopp** [comment]
> 
> 
> deleting history doesn't work either.
> 
> https://pastebin.com/RkBdJFcu

You're not using the latest build from https://github.com/Zingabopp/BeatSync/actions

**Comment by Tommy2678** [comment]
No clue how to download from there, just got it from releases.

**Comment by Zingabopp** [comment]
Just click the latest build and scroll down below all the build warnings (and be logged into GitHub).

**Comment by Tommy2678** [comment]
https://pastebin.com/sjJS2pJN

**Comment by Tommy2678** [comment]
still won't work

**Comment by Epidilius** [comment]
I got it to work. I commented out lines 57-61 of file `DirectoryTarget.cs`:

`if (!entry.AllowRetry)
{
    state = SongState.NotWanted;
    entry.Flag = HistoryFlag.Deleted;
}`

I am now downloading all 600+ of my bookmarked songs.

**Comment by Zingabopp** [comment]
Yeah, now you'll have to delete the history file to get rid of the 404s in it. I'll have to fix that for the release.

**Comment by Tommy2678** [comment]
Alright, deleted the history file, gonna see how it works now, update ya when i'm done.

**Comment by Tommy2678** [comment]
thanks for the live support hahah

**Comment by rusozoll** [comment]
For what it's worth, it's downloading my thousand-ish bookmarks now, no issues. Pulled the updated build, set up a new config, deleted the history. Nothing else.

**Comment by Zingabopp** [comment]
Nothing really changed except the BeatSaver API URLs, the BeatSaver feeds, and song detail structure. Everything else is the same.

**Comment by 0ww** [comment]
> For what it's worth, it's downloading my thousand-ish bookmarks now, no issues. Pulled the updated build, set up a new config, deleted the history. Nothing else.

@rusozoll That did not work for me. Did you only delete `steamapps\common\Beat Saber\UserData\BeatSyncHistory.json` ?

**Comment by partypalme** [comment]
Hi, I'm getting a lot of RateLimit-Errors now. Is there some kind of API key involved?

> [Warning @ 2021-08-12 19:59:36 | SongFeedReader]: Try 0: Rate limit exceeded on url, https://api.beatsaver.com/maps/hash/a8f0463483930857ce37519399cebab3c6a1fce7, retrying in 22 seconds

**Comment by Zingabopp** [comment]
> 
> 
> Hi, I'm getting a lot of RateLimit-Errors now. Is there some kind of API key involved?
> 
> > [Warning @ 2021-08-12 19:59:36 | SongFeedReader]: Try 0: Rate limit exceeded on url, https://api.beatsaver.com/maps/hash/a8f0463483930857ce37519399cebab3c6a1fce7, retrying in 22 seconds

I'm guessing it's my leftover code for old Beat Saver's rate limit. I had it trying to predict the rate limit, but new Beat Saver doesn't have rate limits (yet).

**Comment by AsmodeusCruentus** [comment]
> Yeah, now you'll have to delete the history file to get rid of the 404s in it. I'll have to fix that for the release.

as of 16th of august, is there any news of an update?
tried the recommened things in these comments, but even after deleting history and attempting to run again.
still brings error 404 not found on a bunch of songs aswell giving me an error that the history files doesn't exist.

Not rushing at all, you take your time :D
was just curious if there were any news :)

**Comment by Halki-Y** [comment]
> 
> 
> > Yeah, now you'll have to delete the history file to get rid of the 404s in it. I'll have to fix that for the release.
> 
> as of 16th of august, is there any news of an update?
> tried the recommened things in these comments, but even after deleting history and attempting to run again.
> still brings error 404 not found on a bunch of songs aswell giving me an error that the history files doesn't exist.
> 
> Not rushing at all, you take your time :D
> was just curious if there were any news :)

Hey mate, the artifact for the latest action (Submodule Update as of typing) is working for me. Just remember to delete only the songs that are 404'ing in the BeatSyncHistory.json, so just this part for each of the songs:
```
{
    "Key": "xyz",
    "Value": {
      "SongInfo": "abc",
      "Flag": "Downloaded",
      "Date": "2021-08-17T18:22:11.0582612+10:00"
    }
  },
```
Apologies if you have already tried that and I just repeated everything to you.

**Comment by AsmodeusCruentus** [comment]
> Apologies if you have already tried that and I just repeated everything to you.

Thank you, I hadn't thought of downloading at the bottom of action, silly me, works flawlessly, Thank  you for pointing it out even though it was written in the comments earlier, I clearly just missed it.
Thank you!

**Comment by Zingabopp** [comment]
Beta release published in [Releases](https://github.com/Zingabopp/BeatSync/releases). Any issues with the beta can be posted in their own Issue thread.
