### ISSUE TITLE
Skipping all bookmarked bsaber songs

### ISSUE THREAD

**Issue by FroznFoton** [Zingabopp/BeatSync#47]
Hello Zingabopp, 

Great utility you have here, been using it for years.  Today I downloaded the latest beta version to grab some new songs from bsaber (haven't swung my sabers in several months) and for whatever reason I can't seem to get the songs to download.  

I recognize the disclaimer you have on the main README and grabbed the beta.  

I'm relatively sure I've configured the *.JSON files corrrectly, but I tagged about 25 new songs in bsaber and the plugin appears to have skipped them.  To test this further, I renamed by CustomLevels folder to "CustomLevels_old" to see if I could force the applet to redownload all of the songs and it acknowledged that the folder was missing, created a new "CustomLevels" folder but still appears to have skipped all 480 songs that I've favorited.  

I tried redownloading the beta version of the plugin and set it all up again to the same result.  

![Screenshot 2021-10-12 224253](https://user-images.githubusercontent.com/54485298/137057988-e1d7d93c-e925-441b-9c59-6c547d655ca5.png)

**Comment by Zingabopp** [comment]
Delete `BeatSyncHistory.json` from your UserData folder

**Comment by FroznFoton** [comment]
Aha, thank you.  I saw reference to that in some of the closed requests but I didn't realize where that file was (thought it was in the BeatSync install folder not in the BeatSaber install folder)
