### ISSUE TITLE
BeatSync Not Working Due to Beat Saber Update?

### ISSUE THREAD

**Issue by nancys13** [Zingabopp/BeatSync#7]
Just installed BeatSync today. It's getting an error message part way through and stopping. Beat Saber just did a big update to include a 360 degree feature. Don't know if that's related, but wanted to let you know. Would love to use this mod if I can get it working. Unfortunately I'm on a different computer right now so can't get you a screen shot.

**Comment by Zingabopp** [comment]
BeatSync is broken right now, not so much because of the update directly but because CustomUI is dead and so is BeatSaverDownloader for the moment. Probably won't be released until PlaylistCore is (Downloader used to handle playlists, PlaylistCore will be taking that over.)

**Comment by nancys13** [comment]
Aw, too bad!  But thanks for answering so quickly.  Do you have any idea when PlaylistCore might be released?

**Comment by Zingabopp** [comment]
No idea on that one, it's mostly working now.

**Comment by sbenrap** [comment]
I love Beat Sync and waiting for an update to 1.6 as well. Any news you can share?

**Comment by Zingabopp** [comment]
Still waiting on PlaylistCore to be released (I already have it working with the new Blister playlist format). I also have to stop being lazy and remake the UI in BSML, which won't take too long.

**Comment by sbenrap** [comment]
Thanks for the update, glad to know you are keeping support for this excellent mod :)

**Comment by nancys13** [comment]
Thanks for the update!

**Comment by WhiteZeroX** [comment]
PlaylistCore seems pretty dead, no commits since last July

**Comment by Zingabopp** [comment]
At this point it's mostly my laziness, and wanting to redo some of it to make a separate console version (SyncSaberService) that can share code with the mod to make them both easier to maintain. PlaylistCore works, although apparently some people are having performance issues with the Blister library.

**Comment by sbenrap** [comment]
Yes, I ended up uninstalling Blister. The current way I can play my playlists is with PlaylistLoaderPlugin but indeed it is not as robust as PlaylistCore. For now I load up my 1.5 backed up version, download new songs and copy them over to 1.6.2
Thanks for the updates!

**Comment by Delivator** [comment]
Soo how's things going?

**Comment by IngwiePhoenix** [comment]
It's possibly worth pointing to this: https://github.com/Zingabopp/SyncSaberService
Whilst not being an extension to Beat Saber itself, its still there :)

**Comment by Zingabopp** [comment]
It's still slowwwwly going. Pretty sure SyncSaberService no longer works because at some point Beat Saver stopped ignoring case on the hashes, and SyncSaberService uses all  uppercase hashes X_x. I'll have a replacement for SyncSaberService at about the time i finish BeatSync.
